# Generated by Django 5.1.7 on 2025-05-16 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_token_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='prev_order_ids',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
