# Generated by Django 5.1.7 on 2025-05-16 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_prev_order_ids'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='prev_order_ids',
            new_name='orders',
        ),
    ]
