# Generated by Django 5.1.7 on 2025-05-16 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_prev_order_ids_profile_orders'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='orders',
            new_name='positions',
        ),
    ]
