# Generated by Django 5.2.1 on 2025-05-18 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_profile_positions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='positions',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
