# Generated by Django 5.2.1 on 2025-05-25 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_profile_positions'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ytd_capital_gain',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
