# Generated by Django 5.2.1 on 2025-05-31 06:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_post_title_post_symbol_post_type'),
        ('users', '0009_trade'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_id', models.CharField(max_length=64)),
                ('symbol', models.CharField(max_length=16)),
                ('qty', models.DecimalField(decimal_places=4, max_digits=20)),
                ('side', models.CharField(max_length=4)),
                ('filled_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('buy_price', models.DecimalField(decimal_places=4, max_digits=20)),
                ('posted', models.BooleanField(default=False)),
                ('dismissed', models.BooleanField(default=False)),
                ('post', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-filled_at',),
                'unique_together': {('user', 'position_id')},
            },
        ),
        migrations.DeleteModel(
            name='Trade',
        ),
    ]
