# Generated by Django 5.2.1 on 2025-05-31 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_position_delete_trade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='post',
        ),
    ]
