# Generated by Django 5.2.1 on 2025-06-02 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_remove_position_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='positions',
        ),
        migrations.AddField(
            model_name='position',
            name='capital_gain',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='position',
            name='current_price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='position',
            name='unrealized_gain',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='buy_price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True),
        ),
    ]
