# Generated by Django 5.2.1 on 2025-06-02 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_remove_profile_positions_position_capital_gain_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='buy_price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='position',
            name='capital_gain',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='position',
            name='current_price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='position',
            name='qty',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='position',
            name='unrealized_gain',
            field=models.FloatField(default=0.0),
        ),
    ]
