# Generated by Django 5.2.1 on 2025-06-02 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_position_buy_price_alter_position_capital_gain_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='buy_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='position',
            name='sell_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
