# Generated by Django 5.2.4 on 2025-07-31 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_position_buy_date_position_sell_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='price_jan1',
            field=models.FloatField(default=0.0),
        ),
    ]
