# Generated by Django 5.2.4 on 2025-10-12 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_strategy_purchase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='strategy',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='strategy',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='following',
        ),
        migrations.DeleteModel(
            name='Purchase',
        ),
        migrations.DeleteModel(
            name='Strategy',
        ),
    ]
