# Generated by Django 5.2.4 on 2025-10-15 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_profile_following'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='position',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='position',
            name='sell_price',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
