# Generated by Django 5.2.1 on 2025-05-24 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
        migrations.AddField(
            model_name='post',
            name='symbol',
            field=models.CharField(default='', max_length=4),
        ),
        migrations.AddField(
            model_name='post',
            name='type',
            field=models.CharField(default='', max_length=4),
        ),
    ]
