# Generated by Django 5.2.1 on 2025-05-31 22:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_post_title_post_symbol_post_type'),
        ('users', '0011_remove_position_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='position',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.position'),
        ),
    ]
