# Generated by Django 5.2.1 on 2025-05-31 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_position'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='type',
            new_name='side',
        ),
    ]
